import { describe, expect, it } from "vitest";
import { execFile } from "node:child_process";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

import {
  SovereignDevelopmentRuntime,
  GitDevelopmentAdapter,
  developmentProposalSchema,
  digestText,
  proposalDigest,
  requiredApprovalStatement,
  type DevelopmentAdapter,
  type DevelopmentProposal,
  type DevelopmentWorkspace,
} from "../packages/development/src/index.js";

const before = "export const value = 1;\n";
const after = "export const value = 2;\n";
const added = "# Generated by IRIS\n";
const now = "2026-08-05T09:00:00-06:00";

function proposal(): DevelopmentProposal {
  return developmentProposalSchema.parse({
    proposalId: "proposal_wave-10-graduation",
    objective: "Perform an exact bounded multi-file self-upgrade.",
    canonicalRepository: "stoic1712-IRIS/IRIS",
    baseRevision: "a".repeat(40),
    branch: "iris/wave-10-graduation-proof",
    allowedPaths: ["packages/example", "docs/evidence"],
    forbiddenPaths: ["docs/governance", ".github"],
    changes: [
      {
        path: "packages/example/src/value.ts",
        operation: "update",
        beforeDigest: digestText(before),
        afterDigest: digestText(after),
        content: after,
        rationale: "Upgrade the bounded fixture behavior.",
      },
      {
        path: "docs/evidence/iris-upgrade.md",
        operation: "create",
        beforeDigest: null,
        afterDigest: digestText(added),
        content: added,
        rationale: "Preserve upgrade evidence.",
      },
    ],
    commands: [
      ["pnpm", "test"],
      ["pnpm", "build"],
    ],
    requiredChecks: ["tests", "build", "independent-verification"],
    checkpointRemote: "private-checkpoint",
    rollback: { strategy: "revert", preserveHistory: true },
    cleanup: { deleteWorkspace: true, terminatePaidResources: true, verifyProviderZero: true },
    model: { provider: "ollama", name: "qwen3:8b" },
    createdAt: now,
  });
}

function approval(current = proposal()) {
  return {
    approvalId: "approval_wave-10-graduation",
    proposalId: current.proposalId,
    proposalDigest: proposalDigest(current),
    authenticatedFounder: "Cristofer Stoic Arellano",
    typedStatement: requiredApprovalStatement(current),
    issuedAt: now,
    state: "issued" as const,
  };
}

class FixtureAdapter implements DevelopmentAdapter {
  files = new Map<string, string>([["packages/example/src/value.ts", before]]);
  findings: string[] = [];
  commandExit = 0;
  remoteEqual = true;
  cleanupResult = true;
  resources: string[] = [];
  cleaned = 0;
  terminated = 0;
  createWorkspace(input: DevelopmentProposal) {
    return Promise.resolve({
      id: "workspace_fixture",
      path: "/tmp/fixture",
      baseRevision: input.baseRevision,
      disposable: true as const,
    });
  }
  readFile(_workspace: DevelopmentWorkspace, path: string) {
    return Promise.resolve(this.files.get(path) ?? null);
  }
  writeFile(_workspace: DevelopmentWorkspace, path: string, content: string) {
    this.files.set(path, content);
    return Promise.resolve();
  }
  deleteFile(_workspace: DevelopmentWorkspace, path: string) {
    this.files.delete(path);
    return Promise.resolve();
  }
  run(_workspace: DevelopmentWorkspace, command: string[]) {
    return Promise.resolve({
      command,
      exitCode: this.commandExit,
      outputDigest: digestText("output"),
    });
  }
  verify() {
    return Promise.resolve([...this.findings]);
  }
  checkpoint() {
    return Promise.resolve({
      commit: "b".repeat(40),
      remoteRevision: this.remoteEqual ? "b".repeat(40) : "c".repeat(40),
    });
  }
  rollbackEvidence(_workspace: DevelopmentWorkspace, checkpoint: string) {
    return Promise.resolve({
      command: `git revert ${checkpoint}`,
      preservesHistory: true as const,
    });
  }
  cleanup() {
    this.cleaned += 1;
    return Promise.resolve(this.cleanupResult);
  }
  terminatePaidResources() {
    this.terminated += 1;
    const old = [...this.resources];
    this.resources = [];
    return Promise.resolve(old);
  }
  providerResources() {
    return Promise.resolve([...this.resources]);
  }
}

describe("Wave 10 proposal and approval contracts", () => {
  it("binds exact content, paths, commands, checkpoint, rollback, cleanup, and model", () => {
    const current = proposal();
    expect(current.changes).toHaveLength(2);
    expect(requiredApprovalStatement(current)).toContain(proposalDigest(current));
  });

  it("rejects traversal, forbidden paths, and incorrect content digests", () => {
    const raw = structuredClone(proposal()) as unknown as Record<string, unknown>;
    const rawChange = (raw.changes as Record<string, unknown>[]).at(0);
    if (rawChange === undefined) throw new Error("Fixture change missing.");
    rawChange.path = "../secret";
    expect(() => developmentProposalSchema.parse(raw)).toThrow();
    const forbidden = structuredClone(proposal()) as unknown as Record<string, unknown>;
    const forbiddenChange = (forbidden.changes as Record<string, unknown>[]).at(0);
    if (forbiddenChange === undefined) throw new Error("Fixture change missing.");
    forbiddenChange.path = "docs/governance/constitution.md";
    expect(() => developmentProposalSchema.parse(forbidden)).toThrow(/forbidden/);
    const mismatch = structuredClone(proposal()) as unknown as Record<string, unknown>;
    const mismatchChange = (mismatch.changes as Record<string, unknown>[]).at(0);
    if (mismatchChange === undefined) throw new Error("Fixture change missing.");
    mismatchChange.content = "different";
    expect(() => developmentProposalSchema.parse(mismatch)).toThrow(/digest/);
  });
});

describe("Wave 10 Sovereign Development Runtime", () => {
  it("denies approval that is not bound to the exact proposal and typed statement", async () => {
    const adapter = new FixtureAdapter();
    const invalid = { ...approval(), typedStatement: "I approve something else." };
    expect(
      await new SovereignDevelopmentRuntime(adapter).execute(proposal(), invalid),
    ).toMatchObject({ status: "denied", cleanupVerified: true, providerZeroVerified: true });
  });

  it("applies multiple files, runs tests/build, independently verifies, checkpoints, verifies remote equality, preserves rollback, and cleans up", async () => {
    const adapter = new FixtureAdapter();
    adapter.resources = ["paid_runner_1"];
    const result = await new SovereignDevelopmentRuntime(adapter).execute(proposal(), approval());
    expect(result).toMatchObject({
      status: "succeeded",
      checkpoint: "b".repeat(40),
      remoteEquality: true,
      cleanupVerified: true,
      providerZeroVerified: true,
      rollback: { preservesHistory: true },
    });
    expect(adapter.files.get("packages/example/src/value.ts")).toBe(after);
    expect(adapter.files.get("docs/evidence/iris-upgrade.md")).toBe(added);
    expect(result.events.map((event) => event.type)).toEqual([
      "DevelopmentApproved",
      "WorkspaceCreated",
      "MultiFileEditApplied",
      "ChecksPassed",
      "IndependentVerificationPassed",
      "RemoteEqualityVerified",
      "RollbackEvidencePreserved",
      "WorkspaceCleanupVerified",
      "PaidResourcesTerminated",
      "ProviderZeroVerified",
    ]);
  });

  it("stops for a new typed approval when independent verification requires repair", async () => {
    const adapter = new FixtureAdapter();
    adapter.findings = [
      "Repair changes exact content and therefore invalidates the approval digest.",
    ];
    const result = await new SovereignDevelopmentRuntime(adapter).execute(proposal(), approval());
    expect(result.status).toBe("repair-reapproval-required");
    expect(result.checkpoint).toBeUndefined();
  });

  it("fails closed on command failure and still cleans workspace and resources", async () => {
    const adapter = new FixtureAdapter();
    adapter.commandExit = 1;
    adapter.resources = ["runner"];
    expect(
      await new SovereignDevelopmentRuntime(adapter).execute(proposal(), approval()),
    ).toMatchObject({ status: "failed", cleanupVerified: true, providerZeroVerified: true });
    expect(adapter.cleaned).toBe(1);
    expect(adapter.terminated).toBe(1);
  });

  it("fails closed when checkpoint and remote are unequal", async () => {
    const adapter = new FixtureAdapter();
    adapter.remoteEqual = false;
    const result = await new SovereignDevelopmentRuntime(adapter).execute(proposal(), approval());
    expect(result.status).toBe("failed");
    expect(result.events.at(-1)?.type).toBe("DevelopmentFailed");
  });

  it("creates, verifies, and removes a real disposable Git worktree", async () => {
    const run = promisify(execFile);
    const repository = await mkdtemp(join(tmpdir(), "iris-wave10-adapter-test-"));
    try {
      await run("git", ["init", "-b", "main"], { cwd: repository });
      await run("git", ["config", "user.name", "IRIS Test"], { cwd: repository });
      await run("git", ["config", "user.email", "iris-test@example.invalid"], { cwd: repository });
      await mkdir(join(repository, "packages/example/src"), { recursive: true });
      await writeFile(join(repository, "packages/example/src/value.ts"), before, "utf8");
      await run("git", ["add", "--", "packages/example/src/value.ts"], { cwd: repository });
      await run("git", ["commit", "-m", "fixture"], { cwd: repository });
      const { stdout } = await run("git", ["rev-parse", "HEAD"], { cwd: repository });
      const current = developmentProposalSchema.parse({
        ...proposal(),
        baseRevision: stdout.trim(),
      });
      const adapter = new GitDevelopmentAdapter({ canonicalPath: repository });
      const workspace = await adapter.createWorkspace(current);
      const first = current.changes.at(0);
      const second = current.changes.at(1);
      if (first === undefined || second === undefined) throw new Error("Fixture changes missing.");
      await adapter.writeFile(workspace, first.path, after);
      await adapter.writeFile(workspace, second.path, added);
      expect(await adapter.verify(workspace, current)).toEqual([]);
      expect(await adapter.cleanup(workspace)).toBe(true);
    } finally {
      await rm(repository, { recursive: true, force: true });
    }
  });
});
